### ISSUE TITLE
Parallel example for .NET

### ISSUE THREAD

**Issue by giang-hai-nguyen** [anshooarora/extentreports-csharp#1]
Hi Anshoo,
Could you please add an example for parallel testing?

thanks,

**Comment by anshooarora** [comment]
There are a few tests that you can see [here](https://github.com/anshooarora/extentreports-csharp/tree/master/RelevantCodes.ExtentReports/RelevantCodes.ExtentReports.Tests) which are running paralleled.

**Comment by bdewindt** [comment]
Hi anshooarora,

Can you please update the link you mentioned above?  It's dead now.

Thank you,
Brad

**Comment by alexp1980** [comment]
I'd like to request this too. I have parallel tests running in C# Visual Studio, but the logs are being merged into one extent name. Would like to know how to split them out. Thanks
