### ISSUE TITLE
Dasboard view not appearing as default view

### ISSUE THREAD

**Issue by brknlpr** [anshooarora/extentreports-csharp#102]
I am configuring the config.xml like below but the script that i provided is not affecting the default view.

    
    <encoding>UTF-8</encoding>
    
    
    
    <protocol>https</protocol>
    
    
    <documentTitle>Test Report</documentTitle>
    
    
    <reportName>Test Report</reportName>
    
    
    
    <testViewChartLocation>bottom</testViewChartLocation>
    
    
    <scripts>
         <![CDATA[ $(document).ready(function() {$('.waves-effect:nth-child(3) a:nth-child(1) i:nth-child(1)').click();});]]>
    </scripts>
    
    
    <styles>
        <![CDATA[
            
        ]]>
    </styles>
</configuration>

Environment Details
Extent report Version used: v3.0.2 C#
Operating System and version: Windows 10
If anyone made it on v3.0.2 can help ?

**Comment by anshooarora** [comment]
You need to do this:

```
$("a[view='dashboard-view']").click();
```

**Comment by brknlpr** [comment]
Hi,
Thanks for the answer but didnt work.
