### ISSUE TITLE
Modifying categories table headers

### ISSUE THREAD

**Issue by brknlpr** [anshooarora/extentreports-csharp#104]
Hi,

Is there any way to configure the namings of headers of the categories table on dashboard programmatically ? 
![image](https://user-images.githubusercontent.com/2790616/36363124-758d4464-154b-11e8-9c69-5e6db726f8ef.png)

Extent Reports version 3.0.2

**Comment by anshooarora** [comment]
Yes, you can use JavaScript to change these.

**Comment by brknlpr** [comment]
thanks for the answer
