### ISSUE TITLE
Huge Screenshots attached in Extent Reports 3.1.0 version

### ISSUE THREAD

**Issue by sivadeepti** [anshooarora/extentreports-csharp#106]
Hi Anshoo,

I have recently upgraded my Nuget packages in my project which included Extent Report 3.1.0. 

And seems like original screenshots are attached into the report without any width tag . Seems like width="10%" is missing in this version. 

Anyways I downgraded to Extent Report 3.0.2 version and its working normal again.

Is it deliberate action or is it a bug??Can you look into this please??

Thanks, 
Deepti

**Comment by anshooarora** [comment]
This was missed in the css file.  It is currently a bug.  An easy fix is to add this to your css in extent-config.xml:

```
.step-details > img {
    width: 10%;
}
```

or:

```
string css = ".step-details > img { width: 10%; }";
htmlReporter.Configuration().CSS = css;
```
