### ISSUE TITLE
When will V3 be released for .NET ??

### ISSUE THREAD

**Issue by vigneshwar-v** [anshooarora/extentreports-csharp#12]

**Comment by anshooarora** [comment]
There is no specific date available, but it will be released a little after the Java 3.0 reaches beta.

**Comment by vigneshwar-v** [comment]
Will .NET Version be released sooner, since java v3 has been released already??

**Comment by anshooarora** [comment]
Yes.. hopefully before this month end if not as early as next week.

**Comment by cazofeifacr** [comment]
What is new in this version v3 ? -Compare vrs the current stable version now 2.4. -  Excellent work and many thanks for this fantastic project.

**Comment by vigneshwar-v** [comment]
This is an excellent work, no doubt on it. But still, I would like to use the BDD version of extent reporting and also, I already merged the extentx in my project, so waiting to update it to extentx 2.0

**Comment by vigneshwar-v** [comment]
Any Updates on this ?? @anshooarora

**Comment by anshooarora** [comment]
Hi @vigneshwar-v,  I have been a little lazy as I hardly work with .NET these days.  About 75% of the API is ready though, only a few existing features from Java need to be ported over along with building the view.  If I get enough time this and next month, we should have the release early Jan, however bandwidth has been very little and haven't focused on open-source as much as I would like to..

**Comment by vigneshwar-v** [comment]
Thanks @anshooarora .. Anyway, kudos for keeping the forum alive and also, many users are there for .NET too...

**Comment by anshooarora** [comment]
The initial release is now available.

156b779dfada187414cf3f4ccf28d85a908151cc
