### ISSUE TITLE
Attach log files instead of Linking

### ISSUE THREAD

**Issue by MaruthachalaMoorthy** [anshooarora/extentreports-csharp#2]
Hi Anshoo,
I need to attach the reports instead of linking it from locally. I am sending email with the reports and we are not able to open the attachment since we just linked from local

**Comment by anshooarora** [comment]
Is it possible to provide the link from a shared path, that is available for all users?

**Comment by anshooarora** [comment]
Closing this issue as there has been no response from OP. Feel free to reopen or create a new ticket if required.
