### ISSUE TITLE
Any plans for supporting C# version?

### ISSUE THREAD

**Issue by IliaFraedom** [anshooarora/extentreports-csharp#21]
Hi @anshooarora
Using your great reporting tool, just curios any plans to update C# version?
Thanks,
Ilia.

**Comment by anshooarora** [comment]
Do you mean version 3?

The initial release is now available. 

156b779dfada187414cf3f4ccf28d85a908151cc

**Comment by IliaFraedom** [comment]
That was fast, thank you:)
