### ISSUE TITLE
Issuses in extentreports v3

### ISSUE THREAD

**Issue by IliaFraedom** [anshooarora/extentreports-csharp#22]
![image](https://cloud.githubusercontent.com/assets/20782688/20466512/972a5c5c-afd9-11e6-94a5-0027b86710af.png)

1) End time and duration are not calculated.
2) Tags not working.
3) Very minor, but just in case - style of text filed is different from demo report.

I'm using specflow 2.1 + nunit 2.6.4.

Here is my adapter code:

` public class ExtentReportSpecflowNunitAdapter
    {
        private readonly ExtentReports _report;
        private ExtentTest _test;

        protected ExtentReportSpecflowNunitAdapter()
        {
            _report = ExtentManager.Instance;
        }

        [BeforeScenario]
        public void BeforeScenarioReport()
        {
            var description = FeatureContext.Current.FeatureInfo.Description;
            var name = TestContext.CurrentContext.Test.Name;
            _test = _report.CreateTest(name,
                description);
        }

        [AfterScenario]
        public void AfterScenarioReport()
        {
            var status = TestContext.CurrentContext.Result.Status;
            switch (status)
            {
                case TestStatus.Failed:
                    _test.Fail("Failed");
                    break;
                case TestStatus.Inconclusive:
                    _test.Skip("Inconclusive");
                    break;
                case TestStatus.Skipped:
                    _test.Skip("Skipped");
                    break;
                default:
                    _test.Pass("Pass");
                    break;
            }
           _report.Flush();
        }

        [AfterStep]
        public void AfterStepReport()
        {
            var stepname = ScenarioStepContext.Current.StepInfo.Text;

            if (ScenarioContext.Current.TestError != null)
            {
                _test.Fail(stepname);
                //TODO: Add screenshot manager configuration - enable fro selenium, disable for Api tests
                ScreenshotManager.AddScreenshotToReport(_test);
                _test.Fail(ScenarioContext.Current.TestError);
            }
            else
            {
                _test.Pass(stepname);
            }
        }
    }`

Could you help me with that, maybe i'm doing something wrong?

P.S. - for some reason github don't understand my code - https://codeshare.io/G8zJB5
P.S.1 - just in case  -report
[TestAutomation.Report.Toolkit.zip](https://github.com/anshooarora/extentreports-csharp/files/602377/TestAutomation.Report.Toolkit.zip)

**Comment by anshooarora** [comment]
Fixed, fixed and fixed.
