### ISSUE TITLE
Feature request - attaching text files (e.g. log files) to the report

### ISSUE THREAD

**Issue by obstar** [anshooarora/extentreports-csharp#23]
Hey,
Is it possible or will be in the future to be able to attach text files to the reports and accessible from the report level(e.g. screenshot can be added to each step)? 
I mean by that like log files from browser, from native app, appium server logs etc.. To make report more complete about reasons why test/step failed. 
Screenshots and videos are great but not always have enough details.

**Comment by alexlazarciuc** [comment]
I totally agree with @obstar. That would be really handy to have,

**Comment by anshooarora** [comment]
You can insert any link using the `<a href='rel/mylink.txt'></a>` markup..
