### ISSUE TITLE
AppendExisting doen't  work for ExtentHtmlReporter

### ISSUE THREAD

**Issue by rudrahotta** [anshooarora/extentreports-csharp#25]
Hi, 
With new new NET Version 3.0.0-alpha-2, we are trying use AppendExisting property to create single local report for scenarios from multiple features files, which doesn't work. This used to work  with 2.40  using replaceExisting parameter.

Is this functionality will be missing in new version? I was looking the code and didn't find any implementation where as ExtentXReporter has the implementation.

**Comment by anshooarora** [comment]
The parsing feature is not yet available as I was checking all the core features.  This will be added in the next beta version.
