### ISSUE TITLE
Status 'Debug' doesn't have implimentation in '3.0.0-alpha-2' .Net

### ISSUE THREAD

**Issue by rudrahotta** [anshooarora/extentreports-csharp#26]
Hi,
We are currently testing out '3.0.0-alpha-2' and found new status 'Debug' has been introduced. But it doesn't work on local HTML report. It shows '?' on report. I was looking at the master branch and It looks like 'GetIcon(Status status)' doesn't have implementation for 'Debug'

Thanks,
Rudra

**Comment by anshooarora** [comment]
The icon has not been added, but will be available in the beta release.  The alpha is only to check all the core features.
