### ISSUE TITLE
extent.AssignProject("TesPprojectName") - not recognized in 3.0.0

### ISSUE THREAD

**Issue by sisillV** [anshooarora/extentreports-csharp#28]
Hi Anshooarora,
I update RelevantCodes with AventStack.ExtentReports and I have 2 questions:

1. AventStack.ExtentReports we can use with extentx-0.2.2-alpha?
2. I can not find way to attach a project. Before i use:
extent.AssignProject("TesPprojectName");
extent.X();
But now I can not find AssignProject() and X()

Can you please tell me how to connect the Project now?

**Comment by anshooarora** [comment]
The latest alpha will work with version 1 of ExtentX.  Download the master copy from ExtentX repo, that will work.  

These will be added in the upcoming version since I wanted to check the core features first.  All ExtentX specific features will be available by the release.
