### ISSUE TITLE
Log messages are not shown in 'Logs' tab in '3.0.0-alpha-2' .Net

### ISSUE THREAD

**Issue by ArtemPychenko** [anshooarora/extentreports-csharp#29]
BDD scenario was used. Although 'ExtentReports extent' variable contains all log messages into '_testRunnerLogCollection' varialble, 'Log' tab in generated html report is empty. Screens in attach.

*All log messages are inside the 'extent' variable before method 'Flush()' is called*
![addedlogs](https://cloud.githubusercontent.com/assets/12795014/21742907/0d3cb524-d501-11e6-81c9-68d9697b3314.png)

*Empty 'Log' tab*
![emptylog](https://cloud.githubusercontent.com/assets/12795014/21742905/0d3872f2-d501-11e6-9543-6ec82a51cae4.png)

*Error inside test step is shown*
![mainpage](https://cloud.githubusercontent.com/assets/12795014/21742906/0d38bd16-d501-11e6-8a4e-361e4083e5a2.png)

**Comment by anshooarora** [comment]
Thanks for the detailed description.  I will have a look and fix this issue.
