### ISSUE TITLE
Missing Constructor 

### ISSUE THREAD

**Issue by JakubMol** [anshooarora/extentreports-csharp#3]
Hi,
It appears that this constructor is missing from the library, I have reinstalled it a few times, using NuGet, but the issue remains.

> var extent = ExtentReports(string filePath, bool replaceExisting)

**Comment by anshooarora** [comment]
What version are you using? The [current version](https://github.com/anshooarora/extentreports-csharp/blob/master/RelevantCodes.ExtentReports/RelevantCodes.ExtentReports/ExtentReports.cs#L90) (2.41.0) would allow this.

**Comment by JakubMol** [comment]
I am running 2.41.0, do you have any suggestion as to what could be causing this ?
