### ISSUE TITLE
Some tests not writing when running in parallel 

### ISSUE THREAD

**Issue by Bithellio** [anshooarora/extentreports-csharp#30]
WHen I run my test suite in parallel using Nunit3 the extent reports doesnt seem to capture all of the tests. maybe 1/2 (if that)  are written into the report so i was wondering if there are any ideas on how to get the tests to write to one file. (I'd Rather not split it all out if i can help it) 
 ive heard people suggest making a "Queue" to write them to the file but i dont know how to go about that. 
any help is appreciated

**Comment by anshooarora** [comment]
Are you still having this issue?  How are you writing to ExtentReports?  Can you share a small sample?

**Comment by Bithellio** [comment]
I Managed to get this working in the end by creating a singleton instance ( using a Lazy<t>) and it all works now.  
Thank you very much for responding though
