### ISSUE TITLE
Configure Timestamp to indicate time zone (est,cst)

### ISSUE THREAD

**Issue by RamamurthyB** [anshooarora/extentreports-csharp#32]
We use extentreports to generate reports that are viewed by people from different timezone.
Please guide me to configure the timestamp to display different time zone est, cst ? and also is there a way to add time zone to the time stamp ?

**Comment by anshooarora** [comment]
We can indicate on which timezone the report was created in.  We can show it at the very top of the report.  Would that work?

**Comment by RamamurthyB** [comment]
Yes Sir, that works. Any high level timelines by when this will be implemented ?

**Comment by anshooarora** [comment]
It will part of the upcoming release, 3.0.2.

**Comment by RamamurthyB** [comment]
Thank you!
