### ISSUE TITLE
Not able to click on file link in ExtentReport in Jenkins.

### ISSUE THREAD

**Issue by quldude** [anshooarora/extentreports-csharp#33]
I have a link in report that is displayed in Jenkins, as follows:

`<a href="\\<ipAddress>\Recordings\Video.avi" target="_blank"><span class="info label">Video</span></a>`

But when clicking on it, nothing happens. If I download the report, im able to click on the link. Do you know why this is happening?

**Comment by anshooarora** [comment]
I would recommend saving videos relative to where the report is and passing the path as:

```
Recordings/Video.avi
```
