### ISSUE TITLE
simple extent report example please?

### ISSUE THREAD

**Issue by jloyzaga** [anshooarora/extentreports-csharp#34]
I'd like to try and install on Visual Studio 2015 and am a newbie at VS. So if I could just get a very simple .soln or some instructions to install and run report so as to be able to see what needs doing to get all the functionality. Can someone give me something?

**Comment by anshooarora** [comment]
You can find a few examples here: 

https://github.com/anshooarora/extentreports-csharp/tree/master/ExtentReports/ExtentReports.Tests

The docs will also become available very soon with a few examples.

**Comment by jloyzaga** [comment]
I sent a .cs to the issues list - that should work but it doesnt
