### ISSUE TITLE
ExtentXReport always with Default name and Default Project

### ISSUE THREAD

**Issue by sisillV** [anshooarora/extentreports-csharp#37]
Hi,
I try to add Project and Report name using:
var extentxReporter = new ExtentXReporter();
extentxReporter.Configuration().ReportName = "Build123";
extentxReporter.Configuration().ProjectName = "MyProject";
extentxReporter.Configuration().ServerURL = "http://localhost:1337/";

var extent = new ExtentReports();
extent.AttachReporter(htmlReporter, extentxReporter);

Like it is shown in the readme file. What I must do to really record this new values?
After I attach the extentXReport in extent object:
![15-3-2017- 15-06-10](https://cloud.githubusercontent.com/assets/8655116/23949809/684f728e-0991-11e7-8970-2860167cde61.jpg)

At the same time when I check ExtentXReport.Configuration() I see the values that I put:
![15-3-2017- 15-08-10](https://cloud.githubusercontent.com/assets/8655116/23949843/8a9fb4a2-0991-11e7-9856-e3b09dc8b43b.jpg)

**Comment by anshooarora** [comment]
Are these values not shown correctly in ExtentX?  I am sorry I don't think I completely understand your question.

**Comment by sisillV** [comment]
Hi Anshooarora,
Yes in ExtentX I see only Default poject and default Report name if I use:
 
var extentxReporter = new ExtentXReporter();
extentxReporter.Configuration().ReportName = "Build123";
extentxReporter.Configuration().ProjectName = "MyProject";
extentxReporter.Configuration().ServerURL = "http://localhost:1337/";

var extent = new ExtentReports();
extent.AttachReporter(htmlReporter, extentxReporter);

This is the problem.
