### ISSUE TITLE
Simple test version 3 not outputting report - why? and where do Iload the xml config?

### ISSUE THREAD

**Issue by jloyzaga** [anshooarora/extentreports-csharp#38]
using NUnit.Framework;
using AventStack.ExtentReports;
using AventStack.ExtentReports.Reporter;
using AventStack.ExtentReports.Reporter.Configuration;
using System;

namespace ExtentDemoYoutube
{
    [TestFixture]
    public class BasicReport
    {
        private ExtentReports extent;
        private ExtentTest test;
        private ExtentHtmlReporter htmlReporter;

        [OneTimeSetUp]
        public void StartReport()
        {
            /*
            string pth = System.Reflection.Assembly.GetCallingAssembly().CodeBase;
            string actualPath = pth.Substring(0, pth.LastIndexOf("bin"));
            string projectPath = new Uri(actualPath).LocalPath;

            string reportPath = projectPath + "Reports\\MyOwnReport.html";
            
            extent = new ExtentReports(reportPath, true);

            extent.AddSystemInfo("Host Name", "Joe Loyzaga")
                .AddSystemInfo("Environment", "QA")
                .AddSystemInfo("User Name", "Joe Loyzaga");

            extent.LoadConfig(projectPath + "extent-config.xml");
            */
            htmlReporter = new ExtentHtmlReporter(@"C:\Git\joesreport.html");
            htmlReporter.Configuration().Theme = Theme.Dark;

            extent = new ExtentReports();

            extent.AttachReporter(htmlReporter);

        }

        [Test]
        public void DemoReportPass()
        {
            test = extent.CreateTest("DemoReportPass");
            Assert.IsTrue(true);
            test.Pass("Assert Pass as condition is True");
        }

        [Test]
        public void DemoReportFail()
        {
            test = extent.CreateTest("DemoReportFail");
            Assert.IsTrue(false);
            // this line of code will never execute as NUnit aborts method execution after a failed assert
            test.Fail("Assert Pass as condition is Fail");

        }

        [TearDown]
        public void GetResult()
        {
            var status = TestContext.CurrentContext.Result.Outcome.Status;
            var stackTrace = "<pre>" + TestContext.CurrentContext.Result.StackTrace + "</pre>";
            var errorMessage = TestContext.CurrentContext.Result.Message;

            if (status == NUnit.Framework.Interfaces.TestStatus.Failed)

            {
                test.Fail(stackTrace + errorMessage);
            }
        }

        [OneTimeTearDown]
        public void EndReport()
        {
            extent.Flush();
        }

    }
}

**Comment by anshooarora** [comment]
It should create a report in this location:

```
string pth = System.Reflection.Assembly.GetCallingAssembly().CodeBase;
string actualPath = pth.Substring(0, pth.LastIndexOf("bin"));
string projectPath = new Uri(actualPath).LocalPath;

string reportPath = projectPath + "Reports\\MyOwnReport.html";     
```

**Comment by jloyzaga** [comment]
searched the computer for that file bit its not there

**Comment by anshooarora** [comment]
here?

```
htmlReporter = new ExtentHtmlReporter(@"C:\Git\joesreport.html");
```

**Comment by jloyzaga** [comment]
no I checked there too. It works once as it finds the nunit tests but 
after that it never finds the tests and never runs them

Don't understand why it works once and never again

**Comment by jloyzaga** [comment]
Got it to work as I had to explicitly update nunit test in the project - nuget does not implicitly do this.

**Comment by younggeezus** [comment]
@jloyzaga Can you please explain what you mean by explicitly update nunit test in the project?
