### ISSUE TITLE
how to add css image? keep getting syntax wrong

### ISSUE THREAD

**Issue by jloyzaga** [anshooarora/extentreports-csharp#39]
htmlReporter.Configuration().CSS= "img[src*="pathTo/myImage.jpg"] "

and how to do it using a file with css?

**Comment by anshooarora** [comment]
To add a file, you would have to use JavaScript..  then you can use CSS to style the image so it fits perfectly in that box.  

Example:  http://stackoverflow.com/questions/941206/jquery-add-image-inside-of-div-tag

**Comment by jloyzaga** [comment]
yes but how in theconfig.xml?
