### ISSUE TITLE
This .soln creates a report but does not use the config.xml - why? both attached

### ISSUE THREAD

**Issue by jloyzaga** [anshooarora/extentreports-csharp#40]
[Uploading ExtentDemoYoutube1.zip…]()

[ExtentDemoYoutube.zip](https://github.com/anshooarora/extentreports-csharp/files/853918/ExtentDemoYoutube.zip)

**Comment by anshooarora** [comment]
I am not able to view either attachment.  Please reattach.

**Comment by jloyzaga** [comment]
[ExtentDemoYoutube1.zip](https://github.com/anshooarora/extentreports-csharp/files/859800/ExtentDemoYoutube1.zip)

**Comment by jloyzaga** [comment]
files attached
