### ISSUE TITLE
Can we use extentreports for codedUI 

### ISSUE THREAD

**Issue by bkandi** [anshooarora/extentreports-csharp#41]
Can we use extentreports for codedUI . 

If yes, could you please provide the sample code to use in codedui

**Comment by anshooarora** [comment]
If it uses .NET and has the ability to use external DLLs, then you should be able to use it.  I don't use CodedUI and have no examples, sorry.  You can refer to the [docs](https://github.com/anshooarora/extentreports-csharp/blob/master/Readme.md) for guidance.
