### ISSUE TITLE
adding a css to report

### ISSUE THREAD

**Issue by jloyzaga** [anshooarora/extentreports-csharp#42]
htmlReporter.Configuration().CSS = htmlReporter.Configuration().CSS = " < div id = ""theDiv"" >< img id = ""theImg""  src = ""theImg.png"" /> Where is the image ?</ div > ";

is this the right code and is this the right syntax for the css within the code?

**Comment by anshooarora** [comment]
No.. you cannot add markup as css. This should be done from js. I will share the usage tomorrow.

**Comment by jloyzaga** [comment]
Thanks
Still cannot get a report from the code I sent you as an attachment - it
builds but just gives me
[image: Inline image 1]

**Comment by anshooarora** [comment]
Use this to add image:

```
$('.brand-logo').text('').append('<img src="image-location">');
```

**Comment by jloyzaga** [comment]
thats not the syntax for C# is it?
