### ISSUE TITLE
Still not able to put image on report using css

### ISSUE THREAD

**Issue by jloyzaga** [anshooarora/extentreports-csharp#43]
The code below outputs the report and the name is correct that I have modified but why doesn't the css work? I used the one you gave me. I'm attaching the report
[joesreport.zip](https://github.com/anshooarora/extentreports-csharp/files/866715/joesreport.zip)

using NUnit.Framework;
using AventStack.ExtentReports;
using AventStack.ExtentReports.Reporter;
using AventStack.ExtentReports.Reporter.Configuration;
using System;

namespace ExtentDemoYoutube
{
    [TestFixture]
    public class BasicReport
    {
        private ExtentReports extent;
        private ExtentTest test;
        private ExtentHtmlReporter htmlReporter;

        [OneTimeSetUp]
        public void StartReport()
        {
           /*
            string pth = System.Reflection.Assembly.GetCallingAssembly().CodeBase;
            string actualPath = pth.Substring(0, pth.LastIndexOf("bin"));
            string projectPath = new Uri(actualPath).LocalPath;

            string reportPath = projectPath + "Reports\\MyOwnReport.html";

            extent = new ExtentReports(reportPath, true);

            extent.AddSystemInfo("Host Name", "Joe Loyzaga")
                .AddSystemInfo("Environment", "QA")
                .AddSystemInfo("User Name", "Joe Loyzaga");

            extent.LoadConfig(projectPath + "extent-config.xml");
      */

         htmlReporter = new ExtentHtmlReporter(@"C:/Git/joesreport.html");
            htmlReporter.Configuration().Theme = Theme.Standard;
            htmlReporter.Configuration().ReportName = "Joes Report 24/03/2017";
            htmlReporter.Configuration().CSS = "$('.brand-logo').text('test image').append('<img src='D:\\Users\\jloyzaga\\Documents\\Visual Studio 2015\\Projects\\ExtentDemoYoutube\\logo_high_res.jpg>')";
            extent = new ExtentReports();

            extent.AttachReporter(htmlReporter);

        }

        [Test]
        public void DemoReportPass()
        {
            test = extent.CreateTest("DemoReportPass");
            Assert.IsTrue(true);
            test.Pass("Assert Pass as condition is True");
        }

        [Test]
        public void DemoReportFail()
        {
            test = extent.CreateTest("DemoReportFail");
            Assert.IsTrue(false);
            // this line of code will never execute as NUnit aborts method execution after a failed assert
            test.Fail("Assert Pass as condition is Fail");

        }

        [TearDown]
        public void GetResult()
        {
            var status = TestContext.CurrentContext.Result.Outcome.Status;
            var stackTrace = "<pre>" + TestContext.CurrentContext.Result.StackTrace + "</pre>";
            var errorMessage = TestContext.CurrentContext.Result.Message;

            if (status == NUnit.Framework.Interfaces.TestStatus.Failed)

            {
                test.Fail(stackTrace + errorMessage);
            }
        }

        [OneTimeTearDown]
        public void EndReport()
        {
            extent.Flush();
        }

    }
}

**Comment by anshooarora** [comment]
The snippet shared was javascript not css.

**Comment by jloyzaga** [comment]
using AventStack.ExtentReports;
using AventStack.ExtentReports.Reporter;
using AventStack.ExtentReports.Reporter.Configuration;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using System;

namespace FrameworkForJoe
{
    [TestFixture]
    public class SampleTest
    {
        private static IWebDriver driver;
        private static ExtentReports extent;
        private static ExtentHtmlReporter htmlReporter;
        private static ExtentTest test;

        [OneTimeSetUp]
        public void SetupReporting()
        {
            htmlReporter = new ExtentHtmlReporter(@"C:\Git\joesreport.html");

            htmlReporter.Configuration().Theme = Theme.Dark;

            htmlReporter.Configuration().DocumentTitle = "JoesDocument";
            htmlReporter.Configuration().JS = "$('.brand-logo').text('').append('<E:\\Downloads\\FrameworkForJoe\\FrameworkForJoe\\caplogo.jpg>')";
            htmlReporter.Configuration().ReportName = "JoesReport";

            extent = new ExtentReports();

            extent.AttachReporter(htmlReporter);
        }

        [SetUp]
        public void InitBrowser()
        {
            driver = new ChromeDriver();
            driver.Manage().Window.Maximize();            
        }

        [Test]
        public void PassingTest()
        {
            test = extent.CreateTest("Passing test");

            driver.Navigate().GoToUrl("http://www.google.com");

            try {
                Assert.IsTrue(true);
                test.Pass("Assertion passed");
            } catch (AssertionException)
            {
                test.Fail("Assertion failed");
                throw;
            }
        }

        [Test]
        public void FailingTest()
        {
            test = extent.CreateTest("Failing test");

            driver.Navigate().GoToUrl("http://www.yahoo.com");

            try
            {
                Assert.IsTrue(false);
                test.Pass("Assertion passed");
            }
            catch (AssertionException)
            {
                test.Fail("Assertion failed");
                throw;
            }
        }

        [TearDown]
        public void CloseBrowser()
        {
            driver.Quit();
        }

        [OneTimeTearDown]
        public void GenerateReport()
        {
            extent.Flush();
        }
    }
}

**Comment by jloyzaga** [comment]
[joesreport (2).zip](https://github.com/anshooarora/extentreports-csharp/files/869881/joesreport.2.zip)

**Comment by jloyzaga** [comment]
@"file:///D:\Users\jloyzaga\Documents\FrameworkForJoe\FrameworkForJoe\Capgemini_logo_high_res-smaller-2.jpg"

would this work? cannot get the syntax to work

**Comment by jloyzaga** [comment]
This is the code I want to put into my html via visual studio and it works
                                                    $('.nav-wrapper').text('').append('<img src="file:///G|/Sydney/Disciplines/Testing/Capgemini_logo_high_res-smaller-2.jpg" width=50% height=100% /> ')

This is the code I’m entering (its not syntactically correct)

         htmlReporter.Configuration().JS = "$('.brand-logo').text('').append('<img src="file:///G|/Sydney/Disciplines/Testing/Capgemini_logo_high_res-smaller-2.jpg" width=50% height=100%/>')";

**Comment by jloyzaga** [comment]
This code works  

          htmlReporter.Configuration().JS = "$('.report-name').text('    Test Report').prepend('<img src=file:///G:/Sydney/Disciplines/Testing/Capgemini_logo_high_res-smaller-2.jpg width=50% height=100%>')";
