### ISSUE TITLE
Extent reports 3 shows screenshots all together at end of report

### ISSUE THREAD

**Issue by alexp1980** [anshooarora/extentreports-csharp#47]
Trying out Extent Reports 3 for .Net and the screen shots are all collected together at the end of the report unlike in version 2 where they correctly displayed where they should...

![image](https://cloud.githubusercontent.com/assets/24917034/24449144/661d4616-146e-11e7-8cfb-a43830b494b1.png)

**Comment by anshooarora** [comment]
See [here](http://extentreports.com/docs/versions/3/net/#insert-screenshots).

```
// adding screenshots to log
test.Fail("details", MediaEntityBuilder.CreateScreenCaptureFromPath("screenshot.png").Build());

// or:
var mediaModel = MediaEntityBuilder.CreateScreenCaptureFromPath("screenshot.png").Build();
test.Fail("details", mediaModel);	
```

```
// adding screenshots to test
test.Fail("details").AddScreenCaptureFromPath("screenshot.png");
```

**Comment by alexp1980** [comment]
Thanks very much, I must have missed that. Working fine now.
