### ISSUE TITLE
C# dll - can you tell me the names of the methods in the .dll and whether you have made it com visible

### ISSUE THREAD

**Issue by jloyzaga** [anshooarora/extentreports-csharp#49]
please see this video

https://www.youtube.com/watch?v=cFCSAWEDijA

**Comment by anshooarora** [comment]
The DLL is not COM visible by default, but we can make it so in the upcoming version.  Marking as an enhancement.

**Comment by jloyzaga** [comment]
please tell me the mthods then please?
