### ISSUE TITLE
is Extentrepts-csharp is not getting updated??

### ISSUE THREAD

**Issue by vigneshwar-v** [anshooarora/extentreports-csharp#5]
I can see some docs/ release notes in extentreports-java. I am an extensive user of extentreports-chsarp, is this .NET version is not geting updated or will I get all features as same as in java version?

**Comment by anshooarora** [comment]
All updates will come to the .NET version also.  Both are at the same version at the moment, Java generally gets updates first followed by .NET and the same will be the case for v3 also.

**Comment by vigneshwar-v** [comment]
Thank you.
