### ISSUE TITLE
ExtentX not working after update 3.0.2

### ISSUE THREAD

**Issue by fasteningcode** [anshooarora/extentreports-csharp#50]
After I update the extent to version 3.0.2, am not able to run the tests which are connected to ExtentX. It was working perfectly before the update.... 

Screenshot attached
![reportserverlibrarybug](https://cloud.githubusercontent.com/assets/19743915/24732798/65f9b192-1ac7-11e7-9c53-8a2d59436892.PNG)

**Comment by anshooarora** [comment]
Can you share your ExtentXReporter instantiating code?

**Comment by anshooarora** [comment]
And also the complete stacktrace.

**Comment by fasteningcode** [comment]
var htmlReporter = new ExtentHtmlReporter(reportPath);
   var extentxReporter = new ExtentXReporter();
 
  extentxReporter.Configuration().ReportName = "Automation Reports";
  extentxReporter.Configuration().ProjectName = "Test Environment";
  extentxReporter.Configuration().ServerURL = "http://fc01.fasteningcode.local:27017/";

   extent.AttachReporter(htmlReporter, extentxReporter);


**Note : The same code was working before the update.

**Comment by anshooarora** [comment]
This should be the url of the ExtentX server:

```
extentxReporter.Configuration().ServerURL = "http://fc01.fasteningcode.local:1337/";
```

In the instantiation, point to where the MongoDB server is running:

```
var extentxReporter = new ExtentXReporter("mongodb-host", mongodb-port);
```

**Comment by fasteningcode** [comment]
Thank you Anshoo

It worked

**Comment by jloyzaga** [comment]
Hi Anshoo,

is the version that is com visible available for download yet?

Joe

**Comment by jloyzaga** [comment]
does this mean its not in the latest version yet?
