### ISSUE TITLE
Screenshot being appended to end of report, rather than on line specified

### ISSUE THREAD

**Issue by kpmck** [anshooarora/extentreports-csharp#52]
I have a function in my TearDown method that includes a screenshot on failure. 

My screenshot is being taken and saved as expected, however, instead of the screenshot being displayed on the failure line I would like it displayed on, it appears at the very bottom of the report.

For example, for the following code I would expect the screenshot to be displayed on the same line as the error message, but it is displayed after the stack trace (which is the last item in the report).

`
test.Log(Status.Fail, "Ending the test " + testname + " with the status FAILED.");
test.Log(Status.Fail, "Error Message: " + errorMessage).AddScreenCaptureFromPath(filePath + filename);
test.Log(Status.Fail, "Stack Trace: " + stackTrace);`

Am I using the `.AddScreenCaptureFromPath(filepath)` incorrectly, or is this expected behavior?

**Comment by anshooarora** [comment]
See [here](http://extentreports.com/docs/versions/3/net/#insert-screenshots).  

```
// adding screenshots to log
test.Fail("details", MediaEntityBuilder.CreateScreenCaptureFromPath("screenshot.png").Build());

// or:
var mediaModel = MediaEntityBuilder.CreateScreenCaptureFromPath("screenshot.png").Build();
test.Fail("details", mediaModel);	
```
