### ISSUE TITLE
When is the next version with enhancements due?

### ISSUE THREAD

**Issue by jloyzaga** [anshooarora/extentreports-csharp#53]
Just want to know when the enhancement to make the dll com visible will be out? Soon I hope....

**Comment by anshooarora** [comment]
Hopefully by end of this week..

**Comment by jloyzaga** [comment]
thats with the com visible enhancement? if so great, if not when will the
enhancement come through?

**Comment by jloyzaga** [comment]
how goes the new version with com visible i it?

**Comment by anshooarora** [comment]
Hi Joe - since there are no other updates currently available, the release has been postponed for now.

**Comment by anshooarora** [comment]
You can use this DLL for now.. 

[ExtentReports.zip](https://github.com/anshooarora/extentreports-csharp/files/974002/ExtentReports.zip)

**Comment by jloyzaga** [comment]
com visible?

**Comment by jloyzaga** [comment]
thank you by the way - If I get it working I'll give you the code..

**Comment by jloyzaga** [comment]
Getting error as not found in any loaded assembly when I am using this code-
Set DotNetObject = DotNetFactory.CreateInstance("ExtenReportLib",
"C:\ExtentReports.dll")

which public class should I use so that the next code works?
Set oTest = CreateObject("ExtentHtmlReporter.htmlReporter")
htmlReporter.Configuration().Theme = Theme.Standard
