### ISSUE TITLE
Images attached to extent report are not displayed in 3.0

### ISSUE THREAD

**Issue by sivadeepti** [anshooarora/extentreports-csharp#67]
I am trying to attach images to my report in my project.

Code:

test.AddScreenCaptureFromPath(@"C:\Users\Public\Pictures\Sample Pictures\Desert.jpeg", "Snapshot below:");

where test is an instance of Extent test.

Please let me know if am missing any thing.
![error](https://user-images.githubusercontent.com/25481709/27325738-461bd12e-55a1-11e7-87d7-13ab89bb54b7.jpg)

**Comment by TheXby** [comment]
nothing else.
Maybe problem with permissions access to the file?!
Try using another file in another folder.
For my case im using as filepath `$"..\\..\\{BaseConfiguration.ScreenShotFolder}\\{Path.GetFileName(DriverContext.ScreenshotFilePath)}"` and it works fine. Absolute path also works fine.

**Comment by sivadeepti** [comment]
Yeah problem solved. 

Used relative paths in the code. AddScreenCaptureFromPath takes relative path (relative to Screenshots folder wherever you save in your system)
