### ISSUE TITLE
ExtentX server no test are displayed.

### ISSUE THREAD

**Issue by wergil123** [anshooarora/extentreports-csharp#69]
Hi Anshooarora,

Im beginner here to set up extentx server for my C# project. I've set up completely all the installation steps. When i triggered my test, there is no any test results shown in localhost:1337.

string reportFilename = string.Concat(TestContext.CurrentContext.Test.Name, "_", DateTime.Now.ToString("ddmmyyyy_hhmmss"), ".html");
string fullPath = Path.Combine("d:\\ExtentReports\\", reportFilename);

ExtentXReporter extentxReporter = new ExtentXReporter("mongodb://localhost:27017/");
extentxReporter.Configuration().ServerURL = "http://localhost:1337/";
extentxReporter.Configuration().ProjectName = ("Test");
var htmlReporter = new ExtentHtmlReporter(fullPath);
Extent = new ExtentReports();
Extent.AttachReporter(htmlReporter, extentxReporter)

Thanks.

Regards,
-Wergil-

**Comment by TheXby** [comment]
Hi.
Html report was created and has a test information?

**Comment by wergil123** [comment]
Hi.

Html report was created successfully. But, there is no test results displayed in the "localhost:1337" extentx server.

**Comment by TheXby** [comment]
Your code looks good enough.
What about mongo console output?
It should be smth like this:
> 2017-06-21T10:09:30.045+0300 I NETWORK  [thread1] connection accepted from 127.0.0.1:64879 #21 (6 connections now open)
2017-06-21T10:09:30.166+0300 I NETWORK  [thread1] connection accepted from 127.0.0.1:64880 #22 (7 connections now open)
2017-06-21T10:09:51.993+0300 I -        [conn22] end connection 127.0.0.1:64880 (7 connections now open)
2017-06-21T10:09:51.994+0300 I -        [conn21] end connection 127.0.0.1:64879 (6 connections now open)

**Comment by wergil123** [comment]
Hi,

mongo console output also look fine. Can we check on the mongo dataset for the test results? How can we check whether the test results were stored properly?

![image](https://user-images.githubusercontent.com/26154023/27371861-03273bf2-5695-11e7-9b52-878cd2f059c4.png)

**Comment by TheXby** [comment]
I dont know how we can check correctness of the data but you can view what stored on you db.
Install any GUI tool for mongo (https://robomongo.org/)
extent table should be present in db

**Comment by anshooarora** [comment]
Use this for instantiation:

```
ExtentXReporter extentxReporter = new ExtentXReporter("localhost");
```
