### ISSUE TITLE
Add Optional Parameters for Log Timestamps

### ISSUE THREAD

**Issue by cameronws** [anshooarora/extentreports-csharp#7]
I'm wanting to create a Report from an already executed test/test set and need to specify the Timestamp on the following levels: Test Start and End Times, Step execution timestamp, Total Time for all tests, from an execution extract of our Test repository. I am currently able to override the start and end times for Tests yet unable to specify the Timestamp on a Step level to match that from the extracted data, as that timestamp is specified/created at the time the Log method is called.

**Comment by anshooarora** [comment]
It is possible to access all logs (and set timestamp) of the test [this way](https://github.com/anshooarora/extentreports-csharp/blob/master/RelevantCodes.ExtentReports/RelevantCodes.ExtentReports/Model/Test.cs#L92):

```
var test = extent.StartTest("Test");
test.GetTest().LogList.ForEach(x => x.Timestamp = DateTime.Now);
```

**Comment by cameronws** [comment]
Not really ideal but it should be fine. Thanks.

**Comment by anshooarora** [comment]
Version 3 will make it much more straight forward but for now, this is the only way possible..
