### ISSUE TITLE
Generating extent report for tests that are in multiple classes.

### ISSUE THREAD

**Issue by bilk199** [anshooarora/extentreports-csharp#71]
Hi!
Is there a way to create consolidated report for tests that are in multiple classes in .NET?

**Comment by anshooarora** [comment]
Yes,  you can if maintaining a single instance of ExtentReports,  similar to:

https://github.com/anshooarora/extentreports-java/blob/master/src/test/java/com/aventstack/extentreports/common/ExtentManager.java

**Comment by mkozak81** [comment]
Hi Anshoo,

I'm pretty new to these things, could you please give an example of that in C# ?
(best would be example with 2 separate classes with 1-2 TCs in each)
Really appreciate
Marcin
