### ISSUE TITLE
How to update feature,scenario and steps count and headline

### ISSUE THREAD

**Issue by MonoAutomation** [anshooarora/extentreports-csharp#72]
![img_20170707_162758](https://user-images.githubusercontent.com/1586248/28046563-24295b2e-6602-11e7-9e5a-47d00c9d2cfe.jpg)
Hello,

I have integrated extent reports dll(c#) and trying to generate reports for BDD...but frankly dont know how to make it proper way.

i have written code like below 
scenario = feature.CreateNode<Scenario>(title);
stepDefinition = ScenarioContext.Current.StepContext.StepInfo.StepDefinitionType.ToString();
stepDefinitionkey = ScenarioContext.Current.StepContext.StepInfo.StepInstance.Keyword.ToString();
if (stepDefinitionkey.Contains("And"))
            {
                step = scenario.CreateNode<And>(stepDescription);//.Info(stepDescription);//.Info("Info");
            }else
            {                
                step = scenario.CreateNode(new GherkinKeyword(stepDefinition), stepDescription);
            }

for steps update:
step.Info("The retry mechanish status is : " + result);
step.Fail("The retry mechanish status is : " + result);

but the output is not as expected, if any one one of the step fails within the parent step, everything will be appeared as RED.
and charts also displaying as tests instead of feature....you refer the attachment.

please help me to implement this and share some samples with working project for BDD.

Regards,
Manam

![Uploading IMG_20170707_162758.jpg…]()
![bdd](https://user-images.githubusercontent.com/1586248/28046606-6b72a67a-6602-11e7-9311-ead260baac16.jpg)

**Comment by anshooarora** [comment]
This is expected:   A Step failure would fail the Scenario which would fail the Feature.  

I will try to create a few samples for .NET BDD but in the meantime, you can refer to https://github.com/email2vimalraj/CucumberExtentReporter which is in Java but it may give you a good idea of how things are implemented in this project.

**Comment by MonoAutomation** [comment]
Thank you for the information. i will go through the link you provided.
