### ISSUE TITLE
Child Test Flushing

### ISSUE THREAD

**Issue by GaneshSwnt** [anshooarora/extentreports-csharp#74]
Is there any way to flush results after each child test execution?
In my case, I have more than 10 long running child tests under main test case. So if I want to see the results I need to wait till last child test to finish. 
Please guide me.
Thanks,

**Comment by anshooarora** [comment]
Yes, you can flush the report at any point of time and see the updated status if you are using version 3.  Simply use:

```
extent.Flush();
```
