### ISSUE TITLE
ExtentReports 3.0.2 - Dependency issue with  'Newtonsoft.Json, Version=10.0.0.0

### ISSUE THREAD

**Issue by nikhil-nana** [anshooarora/extentreports-csharp#77]
The type 'JObject' exists in both 'ExtentReports, Version=3.0.2.0, Culture=neutral, PublicKeyToken=null' and 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral

The above error occurs after incluging the ExtenReports Nuget package into my project. 

Steps
Create a vs 2017 unit testing project 
Include nunit and newtonsoft json 10.x. 
Build. -- no issues. 
Add  JObject Jtoken and jproperty variables to a method. 
Add ExtentReorts via nuget 
Build solution. 
Error occurs. 

Looked up on net for solutions. none worked. unloaded prject check for all references to newtonsoft. only one. cleared bin and obj folder recompiled. Did not help.

**Comment by geeeyetee** [comment]
Duplicates #55

**Comment by meghaagarwal2005** [comment]
I was also having the same issue.i had to remove the reference to Extent Report and remove the package for Extent Report in one of the other projects in which it was using newton library and then did a build for the other project and then it worked.

**Comment by anshooarora** [comment]
Please try with version 3.1.2.  All dependencies are added externally instead of package providing them.
