### ISSUE TITLE
It would be nice if the Timestamp column could be made a little wider

### ISSUE THREAD

**Issue by AnnetteS7** [anshooarora/extentreports-csharp#79]
It would be nice if the Timestamp field was wide enough that the data doesn't wrap, so it all shows on one line. As it stands, the last digit and the AM/PM wraps to the next line, so it can look like something occurred at 2 AM at first glance, for example.
![timestamp wraps](https://user-images.githubusercontent.com/12156451/29135762-38ed6ee2-7d09-11e7-8189-b0544a4eda0d.PNG)
![timestamp with more context](https://user-images.githubusercontent.com/12156451/29135766-3c0cbdf8-7d09-11e7-81a5-0c4f517b4353.PNG)

**Comment by anshooarora** [comment]
You can add this to your config.xml, under styles:

```
<!-- custom styles -->
<styles>
    <![CDATA[
        .log > .timestamp {
            min-width: 175px;
        }
    ]]>
</styles>
```

**Comment by AnnetteS7** [comment]
I only found extent-config.xml on my computer (at C:\<user dir>\.nuget\packages\extentreports\3.0.2\lib). I made the change there, but it hasn't widened the field. Is there anything else I need to do? I played around with increasing the number to 195px and 275px but these also didn't appear to change the width.
![timestamp wraps still](https://user-images.githubusercontent.com/12156451/29276206-d6c9763a-80db-11e7-9ed6-6eee32590fe1.PNG)

**Comment by anshooarora** [comment]
Did you load the config file?

```
htmlReporter.LoadConfig("extent-config.xml");
```

**Comment by AnnetteS7** [comment]
No, I didn't know I needed to do that. Thanks for the info, I will try it.

**Comment by AnnetteS7** [comment]
Is the custom style you suggested only available in the pro version? I'm using the free version. Previously I configured my report at runtime for dark theme, etc. When you mentioned LoadConfig(), I moved those settings to the config file instead. I was able to get that file to load at run time, but only the theme etc. are being applied, and the change for Timestamp width is not. If I comment out the LoadConfig then I still get a report with everything standard, so I don't know where that default configuration is being pulled from. If I knew where that was being pulled from, I could put the custom code there and see if that works. Here's what my extent-config.xml looks like at "\packages\ExtentReports.3.0.2\lib\extent-config.xml":

<?xml version="1.0" encoding="UTF-8"?>
<extentreports>
    <configuration>
        
        
        <theme>dark</theme>
    
        
        
        <encoding>UTF-8</encoding>
        
        
        
        <protocol>https</protocol>
        
        
        <documentTitle>Automation Results</documentTitle>
        
        
        <reportName>Results Report</reportName>
        
        
        
        <testViewChartLocation>bottom</testViewChartLocation>
        
        
        <scripts>
            <![CDATA[
                $(document).ready(function() {
                    
                });
            ]]>
        </scripts>
        
		
		<styles>
			<![CDATA[
				.log > .timestamp {
					min-width: 175px;
				}
			]]>
		</styles>
    </configuration>
</extentreports>

And here is the Timestamp field, still unchanged:

![timestamp wrapping unchanged](https://user-images.githubusercontent.com/12156451/29331543-c3cc8ed8-81ca-11e7-8876-0c94e7467e15.PNG)

**Comment by anshooarora** [comment]
You can copy the `config.xml` (with changes, as shown above) file to any folder and load it after creating an instance of the html reporter:

```
ExtentHtmlReporter reporter = new ExtentHtmlReporter("Extent.html");
reporter.LoadConfig("c:\config.xml");
```

Another way is to load the CSS directly in your code:

```
reporter .Configuration().CSS(".log > .timestamp { min-width: 175px; }");
```

**Comment by AnnetteS7** [comment]
Thank you! I got this to work: htmlReporter.Configuration().CSS = ".log > .timestamp { min-width: 175px; }";

![timestamp has been widened](https://user-images.githubusercontent.com/12156451/29626118-c346aa52-87fb-11e7-8b88-fd04e0031a82.PNG)
