### ISSUE TITLE
Browser Compatibility

### ISSUE THREAD

**Issue by cameronws** [anshooarora/extentreports-csharp#8]
I've noticed that with the generated reports, there are some issues between certain browsers that I have been able to test them on. For example, on Chrome I haven't noticed any issues yet on IE9, the content/icon of the menu items on the left hand side menu are not displayed and the icons for the various filters across all tabs/pages are not displayed or display a weird symbol. In saying that, I'm assuming the icons are based on the font specified by the styling which seems to not be recognized by IE9, so is it possible to make use of more browser friendly fonts/icons instead? Could this maybe be handled in the custom script/style sections of the extent-config.xml?

**Comment by anshooarora** [comment]
Only IE10+ supported.  Extent supports all modern browsers, and unfortunately, IE9 is not.
