### ISSUE TITLE
ExtentReport version 3+ examples for Parallel execution on C#

### ISSUE THREAD

**Issue by HeraNguyen** [anshooarora/extentreports-csharp#80]
Hello,
I am using extent report version 3 and looking for any examples for parallel execution. I read some issues and find #27 that mentions the example for version 3+ will be added but I cannot find any. Please help to guide me on how to use extent report version 3+ for parallel execution. 

Thanks,

**Comment by galenyjl** [comment]
Hi,

I have the same issue. For the latest version 3+, really have no idea how to display it separately in the report and always merged. Can anyone help?

**Comment by anshooarora** [comment]
I have added a few tests here:   https://github.com/anshooarora/extentreports-csharp/tree/master/ExtentReports/ExtentReports.Tests/Parallel

Please send in a pull request and help out the project with a few more styles.  I will try to add a couple more later.

**Comment by bankit2491** [comment]
Hi,
@anshooarora  , while refering your code I found two issue can you please help ?

1) In **ExtentTestManager.cs** ExtentTest 
2) In **BaseFixture.cs**    Status logstatus;

Is there any assembly missing ?
