### ISSUE TITLE
Error on documentation

### ISSUE THREAD

**Issue by aldavr** [anshooarora/extentreports-csharp#81]
Hi Arora,
I just want to let you know on NUnit example documentation has some error that may cause issues.
_extent.Flush(); called twise within TearDown and OneTimeTearDown.

`    [OneTimeTearDown]
    protected void TearDown()
    {
        _extent.Flush();
    }
`
`        _test.Log(logstatus, "Test ended with " + logstatus + stacktrace);
        _extent.Flush();`

**Comment by anshooarora** [comment]
The documentation just provides a few areas where this can be potentially used,  and calling it more times generally has a slight performance impact.
