### ISSUE TITLE
Single Test report option

### ISSUE THREAD

**Issue by cameronws** [anshooarora/extentreports-csharp#9]
It would be great if the template would hide/show the list of tests in the Tests tab when only 1 test was run and added to the report as the name of the 1 and only test is already visible in the "Step details" section.

**Comment by anshooarora** [comment]
I am not sure if I entirely understand the question.  You would like to have a filter for test-names?

**Comment by cameronws** [comment]
No not quite. When generating the report, if only 1 test it added to the report, then the list on the Tests tab should not be visible, similar to the image below.

![image](https://cloud.githubusercontent.com/assets/6597703/17815380/62b56c4e-6634-11e6-98dc-c0187043deae.png)

**Comment by cameronws** [comment]
I managed to get around this my adding this to the script section in the config file:

`var ul = document.getElementById("test-collection");
					var cnt = 0;
					for (var i = 0; i < ul.childNodes.length; i++) {
						if (ul.childNodes[i].nodeName == "LI") {
							cnt++;
						}
					}
					if (cnt == 1) {
						var parent = document.getElementById("test-view");
						var children = document.getElementsByClassName("col _addedCell1");
						for (var i = 0; i < children.length; i++)
						{
							parent.removeChild(children[i]);
						}
					}`

**Comment by anshooarora** [comment]
This would be a little simpler approach:

```
if ($('#test-collection .test').length === 1) { 
	$('#test-view > ._addedCell1').hide();
	$('#test-details-wrapper').toggleClass('_addedCell2').css('width', '100%').css('background', '#fff'); 
}
```

**Comment by cameronws** [comment]
Wasn't sure if query as referenced in the html so I didn't use it in my solution. Would prefer to use yours if it works as desired. Thanks.
