### ISSUE TITLE
 BDD in another language in Gherkin

### ISSUE THREAD

**Issue by rodolfo-asantos** [anshooarora/extentreports-csharp#92]
Is it possible to write the BDD (given, then, and ..) terms in other languages ​​in the scenarios in this way? 
``` // steps
scenario.CreateNode<Given>("Jeff has bought a microwave for $100").Pass("pass");
scenario.CreateNode<And>("he has a receipt").Pass("pass");
scenario.CreateNode<When>("he returns the microwave").Pass("pass");
```
If this is not possible, is there a prediction for ExtentReport to support this functionality?

**Comment by anshooarora** [comment]
This will be added to the csharp version very soon.  This is already available in the Java version.

**Comment by rodolfo-asantos** [comment]
I am waiting anxiously for this update in C #, thanks for replying

**Comment by anshooarora** [comment]
This feature will be released in the professional version followed by community soon.

**Comment by anshooarora** [comment]
This will be part of 3.1.0 along with support for klov server.
